### ISSUE TITLE
Add SEO

### ISSUE THREAD

**Issue by Qodri588** [importantimport/urara#29]
Please add this for seo
https://www.npmjs.com/package/svelte-meta-tags

**Comment by kwaa** [comment]
since Urara already contains most of the content in this library ([Basic](https://github.com/importantimport/urara/blob/main/src/lib/components/head.svelte), [OpenGraph](https://github.com/importantimport/urara/blob/main/src/lib/components/head_opengraph.svelte), ~~JSON-LD~~ HTML Microdata), I don't think it's necessary.

**Comment by kwaa** [comment]
are there any other questions or additional clarifications? If not, I will close this question later.
